version: '2'
services:
  coursemaster3k-app:
    image: coursemaster3k
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://coursemaster3k-postgresql:5432/CourseMaster3K
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  coursemaster3k-postgresql:
    extends:
      file: postgresql.yml
      service: coursemaster3k-postgresql
